//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using DML;
    
    public partial class CountMeInEntities : DbContext
    {
        public CountMeInEntities()
            : base("name=CountMeInEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<UsersToEvent> UsersToEvents { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<GroupInvite> GroupInvites { get; set; }
        public DbSet<GroupRole> GroupRoles { get; set; }
        public DbSet<Group> Groups { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UsersToGroup> UsersToGroups { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
        public DbSet<UserTypesToPermission> UserTypesToPermissions { get; set; }
    }
}
