//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DML
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event : IUnitState
    {
        public Event()
        {
            this.UsersToEvents = new HashSet<UsersToEvent>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int HoursOffset { get; set; }
        public Nullable<int> MaxUsers { get; set; }
        public int GroupID { get; set; }
        public int OwnerID { get; set; }
        public bool IsPublic { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<UsersToEvent> UsersToEvents { get; set; }
    
    
    	#region IUnitState Members
    
        public UnitState UnitState	{ get; set; }
    
        #endregion
    }
}
