//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DML
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupRole : IUnitState
    {
        public GroupRole()
        {
            this.UsersToGroups = new HashSet<UsersToGroup>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool IsModerator { get; set; }
    
        public virtual ICollection<UsersToGroup> UsersToGroups { get; set; }
    
    
    	#region IUnitState Members
    
        public UnitState UnitState	{ get; set; }
    
        #endregion
    }
}
