//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DML
{
    using System;
    using System.Collections.Generic;
    
    public partial class User : IUnitState
    {
        public User()
        {
            this.Events = new HashSet<Event>();
            this.Groups = new HashSet<Group>();
            this.UsersToEvents = new HashSet<UsersToEvent>();
            this.UsersToGroups = new HashSet<UsersToGroup>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int UserTypeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ProfileImageName { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual UserType UserType { get; set; }
        public virtual ICollection<UsersToEvent> UsersToEvents { get; set; }
        public virtual ICollection<UsersToGroup> UsersToGroups { get; set; }
    
    
    	#region IUnitState Members
    
        public UnitState UnitState	{ get; set; }
    
        #endregion
    }
}
