//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DML
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType : IUnitState
    {
        public UserType()
        {
            this.Users = new HashSet<User>();
            this.UserTypesToPermissions = new HashSet<UserTypesToPermission>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool IsAdmin { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<UserTypesToPermission> UserTypesToPermissions { get; set; }
    
    
    	#region IUnitState Members
    
        public UnitState UnitState	{ get; set; }
    
        #endregion
    }
}
