//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DML
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTypesToPermission : IUnitState
    {
        public int ID { get; set; }
        public int UserTypeID { get; set; }
        public int PermissionID { get; set; }
    
        public virtual Permission Permission { get; set; }
        public virtual UserType UserType { get; set; }
    
    
    	#region IUnitState Members
    
        public UnitState UnitState	{ get; set; }
    
        #endregion
    }
}
